---
- name: Config Vim With Plugins
  hosts: all
  gather_facts: yes
  become: no # run with -K to become root

  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"

  tasks:
    - name: Install required dependencies
      yum:
        name: epel-release
        state: present

    - name: Enable PowerTools repository
      command: yum-config-manager --enable PowerTools

    - name: Install dnf
      yum:
        name: dnf
        state: present

    - name: Install dnf-command(copr)
      dnf:
        name: dnf-command(copr)
        state: present

    - name: Add COPR repository for Vim
      copy:
        content: |
          [hnakamur-vim]
          name=COPR repo for vim owned by hnakamur
          baseurl=https://copr-be.cloud.fedoraproject.org/results/hnakamur/vim/epel-7-$basearch/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://copr-be.cloud.fedoraproject.org/results/hnakamur/vim/pubkey.gpg
          enabled=1
          enabled_metadata=1
        dest: /etc/yum.repos.d/hnakamur-vim.repo
      notify: Refresh repository

    - name: Remove conflicting vim-minimal package
      yum:
        name: vim-minimal
        state: absent

    - name: Install Vim 8.2
      yum:
        name: vim-enhanced
        state: present

    - name: Check Vim version
      shell: vim --version | head -n 3
      register: vim_version_output

    - name: Display Vim version
      debug:
        var: vim_version_output.stdout_lines
      
    - name: Ensure git is installed
      yum:
        name: git
        state: latest

    
    - name: Install python-pip package
      yum:
        name: python-pip
        state: latest

    - name: Install required packages
      pip:
        name: yamllint
        state: present
        extra_args: --user

    - name: Ensure dirs exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"
        - "{{ vim_dir }}/pack/plugins/start"
        - ~/.config/yamllint
        - ~/bin

    - name: deploy plgins
      git:
        dest: "{{ vim_dir }}/pack/plugins/start/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        depth : 1
        update: yes
        recursive: no
      loop:
        - name: indentLine
          url: https://github.com/Yggdroot/indentLine.git
        - name: yamlFolds
          url: https://github.com/pedrohdz/vim-yaml-folds.git
        - name: ale
          url: https://github.com/dense-analysis/ale.git

    - name: ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0640

      - name: Create snap alias
      community.general.snap_alias:
        name: vim
        alias: vi
        
  handlers:
    - name: Refresh repository
      command: yum clean expire-cache