---
- name: Config Vim With Plugins
  hosts: localhost
  gather_facts: yes
  become: no

  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"

  tasks:
    - name: Install required dependencies
      yum:
        name: epel-release
        state: present

    - name: Enable PowerTools repository
      command: yum-config-manager --enable PowerTools

    - name: Enable COPR repository for Vim
      command: yum copr enable -y hnakamur/vim

    - name: Uninstall Vim
      yum:
        name: vim
        state: absent

    - name: Install Vim 8.2
      yum:
        name: vim
        state: present

    - name: Check Vim version
      shell: vim --version | head -n 3
      register: vim_version_output

    - name: Display Vim version
      debug:
        var: vim_version_output.stdout_lines
      
    - name: Ensure git is installed
      yum:
        name: git
        state: present

    
    - name: Install python-pip package
      yum:
        name: python-pip
        state: present

    - name: Install required packages
      pip:
        name: yamllint
        state: present
        extra_args: --user

    - name: Ensure dirs exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"
        - "{{ vim_dir }}/pack/plugins/start"
        - ~/.config/yamllint
        - ~/bin

    - name: deploy plgins
      git:
        dest: "{{ vim_dir }}/pack/plugins/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
        - name: indentline
          url: https://github.com/Yggdroot/indentLine.git
        - name: yaml folds
          url: https://github.com/pedrohdz/vim-yaml-folds.git
        - name: ale
          url: https://github.com/dense-analysis/ale.git

    - name: ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0640