---
- name: Config Vim With Plugins RHEL9
  hosts: all
  connection: local # local connection is used because we are running ansible on the same machine
  gather_facts: true
  become: false

  tasks:
  - name: Install Vim
    yum:
      name: vim
      state: present

...
